version: '3'
services:
  server:
    build: 
      context: ./server
    links: 
      - mongo
    ports:
      - '8000:8000'
    environment:
      - MONGO_URI=mongodb://mongo/palindetect

  ui:
    build: 
      context: ./ui
    ports:
      - '3000:3000'
    environment:
     - SERVER_HOST=http://13.57.28.144:8000
  
  mongo:
    image: mongo
    ports:
      - '27017:27017'