version: '3'
services:
  server:
    build: 
      context: ./server
    links: 
      - mongo
    ports:
      - '8000:8000'
    environment:
      - MONGO_URI=mongodb://mongo/palindetect

  ui:
    build: 
      context: ./ui
    ports:
      - '3000:3000'
  
  mongo:
    image: mongo
    ports:
      - '27017:27017'